/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThinkingRouteImport } from './routes/thinking'
import { Route as IndexRouteImport } from './routes/index'

const ThinkingRoute = ThinkingRouteImport.update({
  id: '/thinking',
  path: '/thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thinking': typeof ThinkingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thinking': typeof ThinkingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thinking': typeof ThinkingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/thinking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/thinking'
  id: '__root__' | '/' | '/thinking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThinkingRoute: typeof ThinkingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thinking': {
      id: '/thinking'
      path: '/thinking'
      fullPath: '/thinking'
      preLoaderRoute: typeof ThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThinkingRoute: ThinkingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
